apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-service-healthcheck-exporter.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
