apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-service-healthcheck-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-service-healthcheck-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-service-healthcheck-exporter.fullname" . }}
  namespace: monitoring
