apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-service-healthcheck-exporter.fullname" . }}
  labels:
    {{- include "k8s-service-healthcheck-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "k8s-service-healthcheck-exporter.selectorLabels" . | nindent 4 }}
