apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-service-healthcheck-exporter.fullname" . }}
  labels:
    {{- include "k8s-service-healthcheck-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
